# Generated by Django 5.0.14 on 2026-02-20 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('document_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número de Documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil')], max_length=5, verbose_name='Tipo de Documento')),
                ('role', models.CharField(choices=[('Propietario', 'Propietario'), ('Residente', 'Residente')], default='Residente', max_length=20, verbose_name='Rol')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfonos')),
                ('is_minor', models.BooleanField(default=False, verbose_name='Es Menor de Edad')),
                ('is_elderly', models.BooleanField(default=False, verbose_name='Es Adulto Mayor')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Tiene Discapacidad')),
                ('is_realtor', models.BooleanField(default=False, verbose_name='Inmobiliaria')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Registro')),
                ('data_authorization', models.BooleanField(default=False, verbose_name='Autoriza Datos Personales')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='ResidentialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.CharField(max_length=50, verbose_name='Torre')),
                ('unit_number', models.CharField(max_length=50, verbose_name='Apartamento')),
                ('status', models.CharField(choices=[('Propietario', 'Propietario'), ('Arrendado', 'Arrendado'), ('Desocupado', 'Desocupado')], default='Desocupado', max_length=20, verbose_name='Estado')),
                ('pet_count', models.IntegerField(default=0, verbose_name='Mascotas')),
                ('bicycle_count', models.IntegerField(default=0, verbose_name='Bicicletas')),
                ('parking_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parqueadero')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('authorizations', models.CharField(blank=True, max_length=255, null=True, verbose_name='Autorizaciones')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Unidad Residencial',
                'verbose_name_plural': 'Unidades Residenciales',
                'unique_together': {('tower', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('parking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Parqueadero')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
                ('observations', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residential.residentialunit', verbose_name='Apartamento')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.CreateModel(
            name='ResidentUnitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Es Propietario')),
                ('is_resident', models.BooleanField(default=True, verbose_name='Es Residente')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='residential.person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='residential.residentialunit')),
            ],
            options={
                'verbose_name': 'Asignación de Unidad',
                'verbose_name_plural': 'Asignaciones de Unidades',
                'unique_together': {('unit', 'person')},
            },
        ),
    ]
