# Generated by Django 5.0.14 on 2026-03-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialunit',
            name='is_under_remodelation',
            field=models.BooleanField(default=False, verbose_name='En Remodelación/Obra'),
        ),
        migrations.CreateModel(
            name='UnitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Contrato de Arrendamiento', 'Contrato de Arrendamiento'), ('Certificado de Libertad', 'Certificado de Libertad'), ('Contrato de Obra', 'Contrato de Obra'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='unit_documents/', verbose_name='Archivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('size', models.IntegerField(verbose_name='Tamaño (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='residential.residentialunit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Documento de Unidad',
                'verbose_name_plural': 'Documentos de Unidades',
            },
        ),
    ]
