# Generated by Django 5.0.14 on 2026-03-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_residentialunit_is_under_remodelation_unitdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdocument',
            name='document_type',
            field=models.CharField(choices=[('Contrato de Arrendamiento', 'Contrato de Arrendamiento'), ('Certificado de Propiedad', 'Certificado de Propiedad'), ('Contrato de Obra', 'Contrato de Obra'), ('Otro', 'Otro')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
