# Generated by Django 5.0.14 on 2026-03-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0004_alter_unitdocument_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialunit',
            name='parking_info',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='parking_number',
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('type', models.CharField(choices=[('PRIVADO', 'Privado'), ('VISITANTE', 'Visitante')], default='PRIVADO', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('MANTENIMIENTO', 'Mantenimiento')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='residential.residentialunit', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Parqueadero',
                'verbose_name_plural': 'Parqueaderos',
            },
        ),
    ]
