# Generated by Django 5.0.14 on 2026-03-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0005_remove_residentialunit_parking_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='parking_space',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_assignment', to='residential.parkingspace', verbose_name='Parqueadero'),
        ),
    ]
