# Generated by Django 5.0.14 on 2026-03-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0006_vehicle_parking_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='residential.residentialunit', verbose_name='Apartamento'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Automóvil', 'Automóvil'), ('Camioneta', 'Camioneta'), ('Motocicleta', 'Motocicleta'), ('Bicicleta', 'Bicicleta'), ('Otro', 'Otro')], default='Automóvil', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Color'),
        ),
    ]
